apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service
#spec:
#  type: NodePort
#  selector:
#    app.kubernetes.io/name: frontend
#  ports:
#    - name: http
#      protocol: TCP
#      port: 80
#      targetPort: 80
#      nodePort: 30080